{% set name = "umock-c" %}
{% set version = "2022.08.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/umock-c/archive/b53d51c16355c669b21777c242e5d9de529ec5c7.zip
    sha256: 314ec63d917ba76ad8366313ffde0a1374a7bcaaf375a065822f10314406296e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, exact='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - azure-macro-utils-c >=2020.10.29
  run:
    - azure-macro-utils-c >=2020.10.29

test:
  commands:
    - if not exist %PREFIX%\\Library\\include\\umock_c\\umock_c.h exit 1  # [win]
    - test -f "${PREFIX}/include/umock_c/umock_c.h"  # [not win]

about:
  home: https://github.com/Azure/umock-c
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A pure C mocking library

extra:
  recipe-maintainers:
    - xylar
    - seanyen
